class_name Pal
## Paleta iz Claude Design mockupa (25.07.2026) — jedini izvor boja u igri.

const SKY_TOP := Color("#B9E3F2")
const SKY_MID := Color("#D8EFF8")
const SKY_LOW := Color("#E6F5FA")
const HILL_FAR := Color("#B7DBA4")
const HILL_MID := Color("#9BCB89")
const GRASS := Color("#85C077")
const GRASS_DARK := Color("#6FAE64")
const BARN_RED := Color("#D46B5E")
const BARN_ROOF := Color("#B0544A")
const BARN_TRIM := Color("#F7F0E4")
const SUN := Color("#FFD873")
const SUN_GLOW := Color("#FFE9A8")
const CLOUD := Color("#FFFFFF")
const BUTTON_WHITE := Color("#FDFBF6")
const SHADOW := Color(0.22, 0.33, 0.20, 0.16)  # #385434 na 16%
const OUTLINE := Color("#4A3F3A")
const POND := Color("#8FCBE0")
const FENCE := Color("#EFE3CC")
const TREE_GREEN := Color("#74B36B")
const TRUNK := Color("#A8794F")
const HAY := Color("#E8C173")
const HAY_LINE := Color("#D3A755")
const PATH := Color("#E4D3B4")
const SILO := Color("#EDE3D2")
const FLOWER_PINK := Color("#F3B3C4")
const FLOWER_CREAM := Color("#FFE3A0")

# boje životinja (usklađene sa mockup stilom)
const COW_BODY := Color("#FBF6EC")
const COW_SPOT := Color("#6E655D")
const MUZZLE_PINK := Color("#F7CBD4")
const MUZZLE_PINK_D := Color("#D89AAB")
const HORSE_BODY := Color("#C98E5A")
const HORSE_MUZZLE := Color("#E9D3B6")
const HORSE_MANE := Color("#8A5A33")
const PIG_BODY := Color("#F2A7B8")
const PIG_SNOUT := Color("#E58AA0")
const GOAT_BODY := Color("#EFE8DA")
const GOAT_HORN := Color("#E3D2B4")
const CHICK_BODY := Color("#FDFBF6")
const COMB_RED := Color("#D9534F")
const BEAK_ORANGE := Color("#F2A33C")
const BLUSH := Color("#F2B8BE")
const DUCK_BODY := Color("#F7D954")
const DUCK_BILL := Color("#F2A33C")
const DUCK_BILL_D := Color("#E08A2E")
const EYE := Color("#3B3430")
